# Generated by Django 2.0.13 on 2019-06-23 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('photo1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo4', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo5', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo6', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('article_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
